
=head1 NAME

index - Welcome to the POD Output Plugin


=head1 DESCRIPTION



=head2 Apache Forrest - POD Output Plugin

This plugin allows Forrest files to be output in the Perl Plain Old Documentation (POD) format, text with minimal formatting directives. If on a *nix system with perl installed, see "man perlpod". 





=head2 How to Use the POD Plugin

The plugin needs to be incorporated into your existing build of Forrest. To do this, 




=over 4



=item 1.

C<cd $FORREST_HOME/plugin/ > 


=item 2.

C<$FORREST_HOME/tools/ant/bin/ant local-deploy > 


=back


Once you have the POD plugin installed, it is simply a case of requesting a file with a .pod extension. For example, L<this page as pod|index.pod> . 

To have a POD link created in your project documentation, there are two things you will need to do: 




=over 4



=item *


Edit your C<forrest.properties > file and add C<org.apache.forrest.plugin.output.POD > to the C<project.required.plugin > property. 


=item *


Edit your C<skinconf.xml > and set the C<<disable-pod-link> > element to C<false > . 


=back






=head2 Enable POD Plugin in Dispatcher enabled sites

Some documentation has been started and a POD example is available from the L<dispatcher documentation|http://forrest.apache.org/pluginDocs/plugins_0_80/org.apache.forrest.plugin.internal.dispatcher/examples/> 





