#!/bin/sh

# Copyright 2002-2004 The Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_VARS=`dirname $0`/local-vars-`uname -n`
if [ ! -f "$LOCAL_VARS" ]; then
	echo "Please create a file local-vars-`uname -n` containing local variable definitions"
	exit
fi
. $LOCAL_VARS

# Defaults
[ -z "$BASE" ] && BASE=.
[ -z "$WEBAPP" ] && WEBAPP=$BASE/../webapp
[ -z "$REFRESH_LOG" ] && REFRESH_LOG=$WEBAPP/WEB-INF/refresh_log.txt
[ -z "$TIMEOUT" ] && TIMEOUT=$[20*60]
[ -z "$PIDFILE" ] && PIDFILE=$BASE/overseer.pid


echo BASE=$BASE
echo WEBAPP=$WEBAPP
