#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# set the current working dir as the PROJECT_HOME variable 

cygwin=false;
darwin=false;
case `uname` in
  CYGWIN*) cygwin=true ;;
  Darwin*) darwin=true
           if [ -z "$JAVA_HOME" ] ; then
             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home   
           fi
           ;;
esac

if [ "$cygwin" = "true" ] ; then
  PROJECT_HOME=`cygpath -w "$PWD"`
else
  PROJECT_HOME=`pwd`
fi

if [ -z "$DISPATCHER_HOME" ] ; then
  # use the location of this script to infer $DISPATCHER_HOME

  thisprg="$0"

  # Resolve links - $thisprg may be a symbolic link

  while [ -h "$thisprg" ] ; do
    ls=`ls -ld "$thisprg"`
    link=`expr "$ls" : '.*-> \(.*\)$'`

    if expr "$link" : '/.*' > /dev/null; then
      thisprg="$link"
    else
      thisprg=`dirname "$thisprg"`/"$link"
    fi
  done

  DISPATCHER_HOME=`dirname "$thisprg"`

  # Make it fully qualified

  DISPATCHER_HOME=`cd "$DISPATCHER_HOME" && pwd`
  echo $DISPATCHER_HOME
fi

# Save old ANT_HOME
OLD_ANT_HOME="$ANT_HOME"
unset ANT_HOME
ANT_HOME="$DISPATCHER_HOME/tools/ant"

# ----- Set Up The Runtime Classpath ------------------------------------------

if [ "$cygwin" = "true" ] ; then
  S=';'
  DISPATCHER_DOT_HOME=`cygpath -w "$DISPATCHER_HOME"`
else
  S=':'
  DISPATCHER_DOT_HOME=$DISPATCHER_HOME
fi

# set the ant file to use
ANTFILE="$DISPATCHER_DOT_HOME/build.xml"

CP="$CLASSPATH"
export CP
unset CLASSPATH

for i in $DISPATCHER_HOME/lib/*.jar; do
  if [ "$cygwin" = "true" ] ; then
    LIB=`cygpath -w $i`
  else
    LIB=$i
  fi

  CLASSPATH=$CLASSPATH$S$LIB
done
for i in $DISPATCHER_HOME/lib/api/*.jar; do
  if [ "$cygwin" = "true" ] ; then
    LIB=`cygpath -w $i`
  else
    LIB=$i
  fi

  CLASSPATH=$CLASSPATH$S$LIB
done

export CLASSPATH

echo "Apache Forrest Dispatcher.  Run './dispatch -projecthelp' to list options"
echo
export DISPATCHER_HOME
echo "$ANT_HOME/bin/ant" dispatch --noconfig -buildfile "$ANTFILE" -Dbasedir="$PROJECT_HOME" -emacs "$@"
"$ANT_HOME/bin/ant" dispatcher.dispatch --noconfig -buildfile "$ANTFILE" -Dbasedir="$PROJECT_HOME" -emacs "$@"
RESULT=$?

# ---- Restore Classpath
unset CLASSPATH
CLASSPATH=$CP
export CLASSPATH

# ---- Restore ANT_HOME
# Restore old ANT_HOME
ANT_HOME="$OLD_ANT_HOME"
export ANT_HOME

exit $RESULT
