package org.apache.forrest.examples.wicket;

import java.net.URI;

import org.apache.forrest.core.Controller;
import org.apache.forrest.core.document.AbstractOutputDocument;

import wicket.MarkupContainer;
import wicket.markup.html.basic.Label;
import wicket.markup.html.panel.Panel;

/**
 * A panel to deisplay content generated by Forrest2
 */
public class Forrest2Panel extends Panel {

	public Forrest2Panel(MarkupContainer parent, String id, String strRequestURI) {
		super(parent, id);
		try {
			Controller controller = new Controller();
			URI requestURI = new URI(strRequestURI);
			AbstractOutputDocument doc;
			doc = controller.getOutputDocument(requestURI);
			Label label = new Label(this, "content", doc.getContentAsString());
			label.setEscapeModelStrings(false);
		} catch (Exception e) {
			new Label(this, "content",  
					"Unable to process request with Forrest2: "
							+ e.getMessage());
		}
	}

}
