#!/bin/sh

###################################################
# A dubious script which commits generated website
# contents to xml-site/targets/$MODULE 
###################################################
MODULE=${1:-xml-forrest}
case $MODULE in
	xml-forrest) TARGET="forrest" ;;
        xml-forrest-template) TARGET="forrest-sample" ;;
esac
[ -z "$TARGET" ] && echo "Unknown module: $MODULE" && exit;

. `dirname $0`/local-vars
if [ -z "$XML_SITE" ]; then
	echo "Please set the XML_SITE var in local-vars-`uname -n`"
	exit
fi	
SRC_DIR=$WEBAPP/sites/$MODULE
if [ ! -d "$SRC_DIR" ]; then
  echo "Expected website contents in $SRC_DIR"
  exit
fi
LIVECVS=$XML_SITE/targets/$TARGET
if [ ! -d "$LIVECVS" ]; then
  echo "Expected checked-out xml-site/ HTML in non-existent directory $LIVECVS"
  exit
fi
echo "Updating $LIVECVS from $SRC_DIR"
pushd .
cd $LIVECVS
cvsco
echo cvs up -dP
echo "Copying generated docs to xml-site.."
echo "  src  : $SRC_DIR/*"
echo "  dest : $PWD" 
cp -r -p $SRC_DIR/* .
function addfiles()
{
  echo "addfiles '$@'"
  local TXTFILES
  local BINFILES
local DIRS
  for i in $@; do
    #echo "Processing $i.."
    if [ -d "$i" ]; then
      echo "Directory: $i"
      DIRS="$DIRS $i"

      continue
    fi
    local MIME=`file -bi $i 2>/dev/null`
    unset istext
    echo $MIME | grep text > /dev/null && istext="yes"
    if [ "$istext" = "yes" ]; then
      echo "Adding as TEXT ($MIME): $i"
      TXTFILES="$TXTFILES $i"
    else
      echo "Adding as BINARY ($MIME): $i"
      BINFILES="$BINFILES $i"
    fi
  done
  [ ! -z "$TXTFILES" ] && cvsdo add $TXTFILES
  [ ! -z "$BINFILES" ] && cvs add -kb $BINFILES
  if [ ! -z "$DIRS" ]; then
    echo "Processing dirs $DIRS"
    for d in $DIRS; do
      echo "Processing dir $d"
	  unset newfiles ; newfiles=`find $d -type f -not -path "*CVS*"`
	  unset newdirs ; newdirs=`find $d -type d -not -name "CVS" | tr '\n' ' '`
	  echo "  dirs: '$newdirs'"
	  echo "  files: '$files'"
          cvs add $newdirs
	  addfiles $newfiles
    done
  fi
  unset TXTFILES BINFILES DIRS
}
echo "Generating list of new-to-CVS files.."
NEW_FILES=`cvs up | grep '^\?' | cut -d\  -f 2`
#echo "Adding new files to CVS: $NEW_FILES"
addfiles $NEW_FILES

cvs up > /tmp/cvslist 2>&1
echo "Now committing to CVS"
#cvs ci -m "Automatic publish at `date` by forrestrunner."
#cvs ci
popd
echo "xml-site update complete!"
