
=head1 NAME

changes - History of Changes


=head1 DESCRIPTION

L<changes.rss> 



=head2 Version 0.1 (unreleased)



=head3 Changes to Project Administration




=over 4



=item *


[icon: add] Initial pod output plugin. Just removed the functionality from the Forrest core and added as a plugin. (RFT) 


=item *


[icon: update] Changed name to bring into line with new naming conventions. (RDG) 


=back








